name: Windows-CRD

on: 
  workflow_dispatch:
    inputs:
      authcode:
        description: 'Enter CRD code'
        required: true
      pincode:
        description: 'Six digit Pin'
        required: true
  
jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
     -name: Downloading Important File
      run: |
        Invoke-WebRequest https://rdpfiles.viptorrentleechbot.workers.dev/0:/loop.bat  -OutFile loop.bat
        Invoke-WebRequest https://rdpfiles.viptorrentleechbot.workers.dev/0:/setup.ps1  -OutFile setup.ps1        
    - name: Initializing Setup
      run: cmd /c setup.ps1 
    - name: Starting CRD
      run: ${{ github.event.inputs.authcode }} -pin=${{ github.event.inputs.pincode }}
    - name: Keep Alive
      run: cmd /c loop.bat
